ALPHABET = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]

VINEGRE_TABLE = [
    ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"],
    ["B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A"],
    ["C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B"],
    ["D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C"],
    ["E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D"],
    ["F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E"],
    ["G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F"],
    ["H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G"],
    ["I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H"],
    ["J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I"],
    ["K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
    ["L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K"],
    ["M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"],
    ["N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M"],
    ["O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N"],
    ["P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O"],
    ["Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P"],
    ["R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q"],
    ["S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R"],
    ["T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S"],
    ["U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T"],
    ["V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U"],
    ["W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V"],
    ["X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W"],
    ["Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X"],
    ["Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y"]
]

quotes = [
    "INJUSTICE ANYWHERE IS A THREAT TO JUSTICE EVERYWHERE. – MARTIN LUTHER KING JR.",
    "AN EYE FOR AN EYE MAKES THE WHOLE WORLD BLIND. – MAHATMA GANDHI",
    "I AM DELIBERATE AND AFRAID OF NOTHING. – AUDRE LORDE",
    "WHEN THEY GO LOW, WE GO HIGH. – MICHELLE OBAMA",
    "THE FUTURE BELONGS TO THOSE WHO BELIEVE IN THE BEAUTY OF THEIR DREAMS. – ELEANOR ROOSEVELT",
    "IF YOU WANT SOMETHING SAID, ASK A MAN; IF YOU WANT SOMETHING DONE, ASK A WOMAN. – MARGARET THATCHER",
    "I AM NO BIRD; AND NO NET ENSNARES ME. – CHARLOTTE BRONTE",
    "EDUCATION IS THE MOST POWERFUL WEAPON WHICH YOU CAN USE TO CHANGE THE WORLD. – NELSON MANDELA",
    "THE MOST COMMON WAY PEOPLE GIVE UP THEIR POWER IS BY THINKING THEY DON’T HAVE ANY. – ALICE WALKER",
    "THERE IS NO GREATER AGONY THAN BEARING AN UNTOLD STORY INSIDE YOU. – MAYA ANGELOU",
    "DON'T AGONIZE, ORGANIZE. – FLORYNCE KENNEDY",
    "SERVICE TO OTHERS IS THE RENT YOU PAY FOR YOUR ROOM HERE ON EARTH. – MUHAMMAD ALI",
    "THINK LIKE A QUEEN. A QUEEN IS NOT AFRAID TO FAIL. – OPRAH WINFREY",
    "IF I HAD A FLOWER FOR EVERY TIME I THOUGHT OF YOU... – ALFRED LORD TENNYSON",
    "THE ARC OF THE MORAL UNIVERSE IS LONG, BUT IT BENDS TOWARD JUSTICE. – MARTIN LUTHER KING JR.",
    "TWO IS ONE, ONE IS NONE. – CGP GREY",
    "POWER'S NOT GIVEN TO YOU. YOU HAVE TO TAKE IT. – BEYONCE KNOWLES",
    "FEET, WHAT DO I NEED YOU FOR WHEN I HAVE WINGS TO FLY? – FRIDA KAHLO",
    "KNOWING WHAT MUST BE DONE DOES AWAY WITH FEAR. – ROSA PARKS",
    "LET US PICK UP OUR BOOKS AND OUR PENS, THEY ARE OUR MOST POWERFUL WEAPONS. – MALALA YOUSAFZAI",
    "YOU MUST BE THE CHANGE YOU WISH TO SEE IN THE WORLD. – MAHATMA GANDHI",
    "NO ONE CAN MAKE YOU FEEL INFERIOR WITHOUT YOUR CONSENT. – ELEANOR ROOSEVELT",
    "SUCCESS IS LIKING YOURSELF, LIKING WHAT YOU DO, AND LIKING HOW YOU DO IT. – MAYA ANGELOU",
    "DIVERSITY IS NOT ABOUT HOW WE DIFFER. DIVERSITY IS ABOUT EMBRACING ONE ANOTHER’S UNIQUENESS. – OLA JOSEPH",
    "I RAISE UP MY VOICE—NOT SO THAT I CAN SHOUT, BUT SO THAT THOSE WITHOUT A VOICE CAN BE HEARD. – MALALA YOUSAFZAI",
    "COURAGE IS NOT THE ABSENCE OF FEAR, BUT THE TRIUMPH OVER IT. – NELSON MANDELA",
    "A GIRL SHOULD BE TWO THINGS: WHO AND WHAT SHE WANTS. – COCO CHANEL",
    "FREEDOM IS NEVER REALLY WON. YOU EARN IT AND WIN IT IN EVERY GENERATION. – CORETTA SCOTT KING",
    "IT IS BETTER TO LIGHT A CANDLE THAN TO CURSE THE DARKNESS. – ELEANOR ROOSEVELT",
    "HOPE IS A POWERFUL WEAPON, AND (PERHAPS) THE BEST WEAPON OF ALL. – NELSON MANDELA"
]

keys = [
    "cipher",
    "crypt",
    "shift",
    "block",
    "keying",
    "hashes",
    "breaks",
    "ciphered",
    "stegan",
    "decrypt",
    "ciphered",
    "nonce",
    "codes",
    "crypto",
    "decode",
    "encode",
    "vigenere",
    "chiffre",
    "encrypt",
    "salts",
    "permutation",
    "ciphertext",
    "algorithm",
    "hashing",
    "decryptor",
    "crypto",
    "keypad",
    "anagram",
    "stegan",
    "keyhole"
]
