ALPHABET = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]

VINEGRE_TABLE = [
    ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"],
    ["B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A"],
    ["C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B"],
    ["D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C"],
    ["E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D"],
    ["F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E"],
    ["G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F"],
    ["H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G"],
    ["I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H"],
    ["J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I"],
    ["K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
    ["L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K"],
    ["M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"],
    ["N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M"],
    ["O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N"],
    ["P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O"],
    ["Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P"],
    ["R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q"],
    ["S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R"],
    ["T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S"],
    ["U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T"],
    ["V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U"],
    ["W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V"],
    ["X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W"],
    ["Y", "Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X"],
    ["Z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y"]
]

quotes = [
    "THE ONLY THING WE HAVE TO FEAR IS FEAR ITSELF. – FRANKLIN D. ROOSEVELT",
    "I THINK, THEREFORE I AM. – RENE DESCARTES",
    "GIVE ME LIBERTY, OR GIVE ME DEATH! – PATRICK HENRY",
    "THAT'S ONE SMALL STEP FOR MAN, ONE GIANT LEAP FOR MANKIND. – NEIL ARMSTRONG",
    "INJUSTICE ANYWHERE IS A THREAT TO JUSTICE EVERYWHERE. – MARTIN LUTHER KING JR.",
    "TWO IS ONE, ONE IS NONE. – CGP GREY",
    "MR. GORBACHEV, TEAR DOWN THIS WALL! – RONALD REAGAN",
    "VENI, VIDI, VICI. – JULIUS CAESAR",
    "THOSE WHO CANNOT REMEMBER THE PAST ARE CONDEMNED TO REPEAT IT. – GEORGE SANTAYANA",
    "FLOAT LIKE A BUTTERFLY, STING LIKE A BEE. – MUHAMMAD ALI",
    "SPEAK SOFTLY AND CARRY A BIG STICK. – THEODORE ROOSEVELT",
    "POWER TENDS TO CORRUPT, AND ABSOLUTE POWER CORRUPTS ABSOLUTELY. – LORD ACTON",
    "THE DIE IS CAST. – JULIUS CAESAR",
    "A HOUSE DIVIDED AGAINST ITSELF CANNOT STAND. – ABRAHAM LINCOLN",
    "TO BE OR NOT TO BE, THAT IS THE QUESTION. – WILLIAM SHAKESPEARE",
    "ASK NOT WHAT YOUR COUNTRY CAN DO FOR YOU – ASK WHAT YOU CAN DO FOR YOUR COUNTRY. – JOHN F. KENNEDY",
    "I HAVE NOT FAILED. I'VE JUST FOUND TEN THOUSAND WAYS THAT WON'T WORK. – THOMAS EDISON",
    "AN EYE FOR AN EYE ONLY ENDS UP MAKING THE WHOLE WORLD BLIND. – MAHATMA GANDHI",
    "HISTORY WILL BE KIND TO ME FOR I INTEND TO WRITE IT. – WINSTON CHURCHILL",
    "THE UNEXAMINED LIFE IS NOT WORTH LIVING. – SOCRATES",
    "LIBERTY, EQUALITY, FRATERNITY. – FRENCH REVOLUTION MOTTO",
    "A JOURNEY OF A THOUSAND MILES BEGINS WITH A SINGLE STEP. – LAOZI",
    "ET TU, BRUTE? – JULIUS CAESAR",
    "WORKERS OF THE WORLD UNITE! – KARL MARX",
    "EDUCATION IS THE MOST POWERFUL WEAPON WHICH YOU CAN USE TO CHANGE THE WORLD. – NELSON MANDELA",
    "ALL MEN ARE CREATED EQUAL. – DECLARATION OF INDEPENDENCE",
    "I DISAPPROVE OF WHAT YOU SAY, BUT I WILL DEFEND TO THE DEATH YOUR RIGHT TO SAY IT. – VOLTAIRE",
    "GIVE ME A LEVER LONG ENOUGH AND A FULCRUM ON WHICH TO PLACE IT, AND I WILL MOVE THE WORLD. – ARCHIMEDES",
    "THE ARC OF THE MORAL UNIVERSE IS LONG, BUT IT BENDS TOWARD JUSTICE. – THEODORE PARKER",
    "BETTER TO DIE STANDING THAN TO LIVE ON YOUR KNEES. – EMILIANO ZAPATA"
]

keys = [
    "cipher",
    "crypt",
    "shift",
    "block",
    "keying",
    "hashes",
    "breaks",
    "ciphered",
    "stegan",
    "decrypt",
    "ciphered",
    "nonce",
    "codes",
    "crypto",
    "decode",
    "encode",
    "vigenere",
    "chiffre",
    "encrypt",
    "salts",
    "permutation",
    "ciphertext",
    "algorithm",
    "hashing",
    "decryptor",
    "crypto",
    "keypad",
    "anagram",
    "stegan",
    "keyhole"
]